"""
Django settings for kutiva project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import dj_database_url

from django.utils.translation import ugettext_lazy as _

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'cqd9i9ua1mo@zbr2r41sm3)pd5__a_r1%4h^=tc^+z9p)z(mfg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'suit',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # for your heroku static serving
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
    'account',
    'cms',
    'screencast'
   ,


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware'
]

ROOT_URLCONF = 'kutiva.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['kutiva/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kutiva.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# These dbconfigs will be active on heroku deployment
db_from_env = dj_database_url.config(conn_max_age=500)
DATABASES['default'].update(db_from_env)

# Honor the 'X-Forwarded-Proto' header for request.is_secure()
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'

# Extra places for collectstatic to find static files.
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'kutiva', 'static'),
)

STATICFILES_STORAGE = 'whitenoise.django.GzipManifestStaticFilesStorage'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Suit admin configurations
SUIT_CONFIG = {
    # 'ADMIN_NAME': 'Admin app name',
    # 'HEADER_DATE_FORMAT': 'l, j. F Y',
    # 'HEADER_TIME_FORMAT': 'H:i',

    # forms
    # 'SHOW_REQUIRED_ASTERISK': False,  # Default True
    # 'CONFIRM_UNSAVED_CHANGES': False, # Default True

    # menu
    # 'SEARCH_URL': 'admin:examples_country_changelist',
    # 'MENU':(
    #     # Rename app and set icon
    #     {'app': 'examples', 'icon':'icon-leaf', 'models': (
    #         'country', 'continent', 'kitchensink'
    #     )},
    #     {'label': 'Integrations', 'icon':'icon-globe', 'models': (
    #         'examples.city', 'examples.category', 'examples.wysiwygeditor',
    #         'examples.reversioneditem', 'examples.importexportitem'
    #     )},
    #
    #     {'app': 'cms', 'label': 'Django CMS', 'icon': 'icon-file', 'models': (
    #         'cms.page',
    #         'snippet.snippet',
    #         'cmsplugin_filer_image.thumbnailoption',
    #         'sites.site',
    #     )},
    #
    #     {'app': 'filer', 'label': 'Filer', 'icon': 'icon-picture',
    #      'url': '/admin/filer/', 'models': (
    #         {'model': 'filer.folder', 'label': 'Browse files'},
    #         {'model': 'filer.folderpermission', 'label': 'Permissions'},
    #     )},
    #     # '-',
    #     {'app': 'auth', 'models': ('user',), 'icon': 'icon-lock'},
    #
    #     {'label': 'Custom view', 'icon':'icon-cog', 'models': (
    #         {'label': 'Custom link', 'url': '/admin/custom/'},
    #         {'label': 'Check out error 404', 'url': '/admin/non-existant/'},
    #     )},
    # ),

    # misc
    'LIST_PER_PAGE': 15
}

AUTO_RENDER_SELECT2_STATICS = False

FILER_ENABLE_PERMISSIONS = True
THUMBNAIL_QUALITY = 100
THUMBNAIL_PROCESSORS = (
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    #'easy_thumbnails.processors.scale_and_crop',
    'filer.thumbnail_processors.scale_and_crop_with_subject_location',
    'easy_thumbnails.processors.filters',
)

LANGUAGES = (
    ('en', _('English')),
    ('fr', _('French')),
    ('ru', _('Russian')),
)

CMS_SHOW_START_DATE = True
CMS_SEO_FIELDS = True

SUIT_CONFIG = {
    'ADMIN_NAME': 'KUTIVA'
}
